### ISSUE TITLE
If someone says No to original message, not the reply from the bot, it should delete the tweet

### ISSUE THREAD

**Issue by william-sheldon** [HUU/MegadomeSays#3]
There is a way to resolve what tweet belongs to what message by looking it up in firebase

**Comment by william-sheldon** [comment]
```
root@megadomesays-staging-vm:/var/lib/megadome-says# node bot.js 
Logged in as megadomesays-staging#2567.
water lttle buidler's message "n" will be tweeted.
Tweet sent, available at https://twitter.com/megadomesays/status/1387570955367505926.
Attempting to delete the tweet referenced in "n".
Something went wrong handling reaction:  Error: Could not find a tweet to delete in n"
    at Object.exports.ExtractTweetId (/var/lib/megadome-says/lib.js:62:15)
    at Client.<anonymous> (/var/lib/megadome-says/bot.js:37:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
